-*- mode: org; mode: visual-line; -*-
#+STARTUP: indent

* algo-2025
** Journal
*** 2026-07-13

- Bulk paramater reflection temporarily kills everything: why?
- Also (cosmetic): better contrast and VU visuals from the matrix grid?
- At some point: swap out Axon 2 for Axon 3 (and refresh base file)

*** 2026-07-12

- Rehearsal: going for predominantly a two-looper configuration (but looking to end the set with some reverb - we either get something out of Replika XT, or swap out Rift for Eos (or plain Replika) - having said which, Replika_XT seems to do diffusion as well (!) - but we've pretty much set up Replika as well now
- Still TODO:
  - [ ] Channels/decoupling for parameter transmission
  - [ ] Optional dB argument for mix paths

**** Instrument Change
***** Max

- Argument setup in =Labels= (for Krell display - reverse order)
- Arguments to =crosspatch= (inputs and/or outputs)
- =Audio= subpatcher: two =route= instances, =ag25.VST3=

***** ClojureScript

- =net.cassiel.algo-2025.devices=: list in =channel-names= (used for numeric routing)
- =net.cassiel.algo-2025.devices=: =param-enums= (if any)
- =setup=: establish base load file, parameter reflection fetch, =unload-all= (is that vestigial?)

*** 2026-07-11

- For feedback: would be nice to have a text box in the patcher for async messages - but Max console is fine for now (check we have support for that)
- =seq.cljs=: the conformer is outside the =reset!= - does it reliably throw an exception?

*** 2026-07-10

- Upsizing: adding Rift and Replika_XT to the matrix
- Generic VST issues: Replika_XT seems to change parameter sets depending on mode (and it has several modes) - the one causing trouble right now is single vs. double delay (though we can't actually switch mode because the parameter name has a =/= in it!)
- Think more clearly about the base state and the total set of parameters we might change (so that we can do group changes as atomic-ish actions with predicable results) - or can we reliably just do reloads from disc? Unlikely for Enso since the speed changes need to be tight in timing
- Need to do reliable timing-spaced actions for device setup etc. (aside from the ones which we sequence on the beat - don't alter those!) - how much stuff can reliably sequence itself and return a channel? Can we really fix =xmit-some-params-now=?
  - If we can make that work, then the kick-off in =setup= with device loading, parameter dictionary population etc. - and DSP and transport load - can be fired in a single action
  - In general: consideration of this method of time-chaining actions (cf. coroutines)
- TODO: can we make =mix-paths= etc. take an optional gain/attenuation level? Right now it's all or nothing (=ctrl/mix= can do that - and also takes an obligatory time!
- More live-code support: tempo? What about ensuring overdrive is on etc.?

*** 2026-07-09

- Make sure overdrive is on (we are sequencing notes, for Microtonic and for Enso speed changes...!)
- =narrative.cljs=: setting up a linear succession of states, testing with Microtonic

*** 2026-07-08

- Need to catch up on Emacs support, in particular C-w and M-w for cut/copy/paste - looks to be a global change, probably in Prelude
- Look into Native Instruments Replika

*** 2026-06-26

- [[https://emacsredux.com/blog/2026/06/20/essential-structured-navigation-and-editing-commands/][Editing]] (Emacs Redux) - =C-M-d= doesn't work, seems to activate Siri - also =C-M-SPC= broken
- =sp-use-paredit-bindings= - =C-S-(/)/{/}= - but also =C-M-left= and =C-M-right=

*** 2026-05-24
**** Review

Reviewing devices - currently we have 8x8:

- (External IO)
- Microtonic (test source?)
- Enso (* 2)
- ODS (* 2)
- Axon (V2!)
- Discord4

**** TODO

- [X] Check the Microtonic can be swapped in/out (looks like it's separate in the matrix)
- [ ] Consider taking out an ODS and swapping in a ShaperBox3 (but that's a hard-wired rhythm)
- [ ] Consider taking out Axon, or at least going for V3
- [ ] No reason why we can't expand past 8x8 for maximum options
- [ ] Check the scripts: many refer to older instruments (e.g. Replika XT) - maybe that one goes back?
- [X] Installations on MacBook Neo
- [X] Longer term: shift away from Figwheel (esp. if we want to use more JS-native libraries)? Look at Shadow CLJS usage in =field-zhen=

**** Startup Procedure

1. Start server: =bb watch-app=: plants port number in =.nrepl-port=
1. =cider-connect-cljs= (not =jack-in=) to attach in Emacs
1. Fire up Node.js process in Max (and check =node.script= console) - =figwheel-main.edn= disables any attempt to launch Node
1. =setup.cljs= for event handler and general setup
1. Teardown (=ctrl/unload-all=) prior to patcher save

** Device Change
*** Max

- Labels subpatcher driving TextBrick (loadbang)
- Labels in crosspatch
- Audio subpatcher: routes and VST instances

*** ClojureScript

- params.cljs has a spec incorporating channel names
- devices.cljs has array of channel names (devices + IO)
- devices.cljs establishes symbolic parameter values per device (partial/optional)
- Individual scripting files

** TO DO
*** Features

- Good known starting points (VST presets)
- Clojure-end errors (somehow) for things like unknown enumerated parameters
- Enso: controlled looping cues, and speed change

*** Code

- We could have a single =ag25.Break= in the multichannel loopback connection
